### ISSUE TITLE
No brush preview when frame is empty

### ISSUE THREAD

**Issue by dacap** [aseprite/Attachment-System#118]
How to reproduce it?

**Comment by Gasparoken** [comment]
This is a side effect of blocking the standby state with the `if` in `hasTileManagementPlugin` here:
https://github.com/aseprite/aseprite/blob/398ca95392450625a44a11815eb51118f2326d7e/src/app/ui/editor/standby_state.cpp#L645-L649)

So, if no attachment is placed, no brush preview on the editor.

This was made to have full plugin control of attachment creation/modification without the automatic rehash/remap actions of Aseprite core.

Perhaps, we can include this issue as a "core tweak" in: https://github.com/aseprite/Attachment-System/issues/127

**Comment by dacap** [comment]
Closing this one, was related to #3882
