### ISSUE TITLE
Attachment Placement

### ISSUE THREAD

**Issue by dacap** [aseprite/Attachment-System#2]
Ability to assign:
- [x] one reference/pivot point to each tile/attachment
- [x] several anchor point to the parent tile/attachment
- [x] assign anchor <-> reference point connection
- [ ] #52
- [x] put anchor points in the canvas one per frame/tile
- [x] a way to display/mark missing reference point per tile in the main window
- [x] navigating through different tiles of the attachment should align the tile with the reference point automatically (e.g. navigation with arrow keys + enter to change the attachment/tile)

**Comment by Gasparoken** [comment]
About: "assign anchor <-> reference point connection"
I'll start a simple parent/children structure implementation:
```
Layer = {
   categories={ categoryID1, categoryID2, etc. },
   folders={
     { name="Folder Name",
       items={ tileIndex1, tileIndex2, ... },
       viewport=Size(columns, rows) }
   parent={ layer1 }
   children={ layer1, layer2, layer3, ... }
} 
```

**Comment by dacap** [comment]
The parent/children relationship must not be specified two times in the properties (e.g. using "parent" we can already construct the list of possible children for a specific layer).
