### ISSUE TITLE
Add delete function in the context menu on images of the base folder

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/Attachment-System#27]
On the Base Folder, the right click context menu only has "New Empty" and "Duplicate". On the other hand additional folders already have the "Delete" function.

**Comment by martincapello** [comment]
There is actually a reason to disallow deleting attachments/tiles from the base folder. The idea is that the base folder contains all the tiles from the tileset, so it wouln't be actually useful to delete tiles. I will revert this change for now.

**Comment by martincapello** [comment]
Okay, I will push it anyway and let the users decide if it is actually useful for them.
