### ISSUE TITLE
Delete an attachment from base set needs remap tiles or a limitation

### ISSUE THREAD

**Issue by dacap** [aseprite/Attachment-System#42]
The new "Delete" option for the base set can delete any tile, but needs to remap tiles (or probably only available for unused tiles).

Initially the Delete option [was added](https://github.com/aseprite/Attachment-System/commit/9ab1addf445105cd6641b79a4ae4102d2ee49552#diff-b5fc35207f612cc5cf73e477ac41172b3a054c61423d7779b3405a13cf15830eR285) for any category/tileset, then [removed for the Base set](https://github.com/aseprite/Attachment-System/commit/8e5f09f66654b75a45ec58bbe15949a0de5bb4c8#diff-b5fc35207f612cc5cf73e477ac41172b3a054c61423d7779b3405a13cf15830eR307) as it was requested, and then re[-added again](https://github.com/aseprite/Attachment-System/commit/019f076092abe70a104b966a4ddec612f1ae941f) but without [remapping tiles](https://github.com/aseprite/Attachment-System/commit/9ab1addf445105cd6641b79a4ae4102d2ee49552#diff-b5fc35207f612cc5cf73e477ac41172b3a054c61423d7779b3405a13cf15830eR82).

**Comment by dacap** [comment]
Just as a side note: The Base set must contain all existent attachments/tiles in the tileset, deleting a tile from the base set must remove it from the tileset.

**Comment by dacap** [comment]
Some work in 3350c82884b2d008902a6c8afdf602d1bb9653e8

**Comment by Gasparoken** [comment]
Ready for review. This last commit adjusts tile indices, tile position in 'tile_view', and manages the tileset in base and non-base folders.
