### ISSUE TITLE
Export all tilesets (categories)

### ISSUE THREAD

**Issue by dacap** [aseprite/Attachment-System#46]
We need a way to export all tilesets, but we need to see how would be the best way to do it (e.g. for general users, and specifically for the Attachment System). *File > Export > Export Tileset* should offer a way to do so, but we can create a customized way if it's needed from the same extension.

**Comment by martincalander** [comment]
The most important thing for me is that it works with the [Aseprite CLI ](https://www.aseprite.org/docs/cli/) api. Preferably inside same .json file as the the --[data](https://www.aseprite.org/docs/cli/#data) <filename.json>. 

In the .json/frames list "filename": "Psycho Boy (Left Arm/Tatoo) 1.ase", "filename": "Psycho Boy (Left Arm/Default) 1.ase" etc. And in .json/meta, either have a list of all attachmentLayers, or have them mixed in with normal layers but have like a layerType: "attachment" or layerType: "layer".

**Comment by dacap** [comment]
Hi @martincalander, I'll be working on this one. I've to think a little more about the output format for tilemaps inside the sprite sheet of if it really worth it (or if there is a standard way to do so in game engines like Unity).

About the CLI, there is no problem, we can create an export script to be used like:

    aseprite -b psycho-boy.aseprite -script export.lua 

Using [-script](https://www.aseprite.org/docs/cli#script) and [-script-param](https://www.aseprite.org/docs/cli#script-param) as needed.

---

Actually, *we already have* an export script that you can use right now: https://github.com/dacap/export-aseprite-file

For example, using:

    aseprite -b freezy-test.aseprite -script export-aseprite-file/export.lua

Will create a `freezy-test` folder with each tileset on its own .png file, and a `sprite.json` with the tilemap data for each cel, here a snippet of the output for the .json file:

```json
{
  "layers": [
    {
      "name": "Char",
      "cels": [ ... ]
    },
    {
      "tileset": -1,
      "name": "Hair",
      "cels": [
        {
          "tilemap": { "tiles": [ 1 ], "height": 1, "width": 1
          },
          "frame": 9,
          "bounds": { "width": 320, "height": 180, "x": 0, "y": 0 }
        },
        {
          "tilemap": { "tiles": [ 1 ], "height": 1, "width": 1 },
          "frame": 10,
          "bounds": { "width": 320, "height": 180, "x": 0, "y": 4 }
        },
        {
          "tilemap": { "tiles": [ 1 ], "height": 1, "width": 1 },
          "frame": 11,
          "bounds": { "width": 320, "height": 180, "x": 0, "y": 12
          }
        },
        {
          "tilemap": { "tiles": [ 1 ], "height": 1, "width": 1 },
          "frame": 12,
          "bounds": { "width": 320, "height": 180, "x": 0, "y": 13
          }
        },
        {
          "tilemap": { "tiles": [ 1 ], "height": 1, "width": 1 },
          "frame": 13,
          "bounds": { "width": 320, "height": 180, "x": 0, "y": 12 }
        },
        {
          "tilemap": { "tiles": [ 1 ], "height": 1, "width": 1 },
          "frame": 14,
          "bounds": { "width": 320, "height": 180, "x": 0, "y": 13 }
        },
        {
          "tilemap": { "tiles": [ 1 ], "height": 1, "width": 1 },
          "frame": 15,
          "bounds": { "width": 320, "height": 180, "x": 0, "y": 12 }
        },
        {
          "tilemap": { "tiles": [ 1 ], "height": 1, "width": 1 },
          "frame": 16,
          "bounds": { "width": 320, "height": 180, "x": 0, "y": 3 }
        }
      ]
    },
    ...
  ],
  "frames": [ ... ],
  "width": 320,
  "tags": [ ... ],
  "height": 180,
  "tilesets": [
    {
      "grid": {
        "tileSize": {
          "height": 180,
          "width": 320
        }
      },
      "image": "freezy-test/tileset1.png"
    },
    {
      "grid": {
        "tileSize": {
          "height": 180,
          "width": 320
        }
      },
      "image": "freezy-test/tileset2.png"
    },
    ...
  ],
  "filename": "freezy-test.aseprite"
}
```
We can create a customized `export.lua` to export the data in any set of images + json (anything that better fit your import code).

**Comment by dacap** [comment]
We've implemented something using ExportSpriteSheet duplicating each layer with its own tileset/category to export all categories on each different layer.

To identify attachment layers, the meta layers will contain an user data like this (`"data": "attachment" `):
```
  "layers": [
   { "name": "Char", "opacity": 255, "blendMode": "normal" },
   { "name": "Arm L/BASE", "opacity": 255, "blendMode": "normal", "data": "attachment" },
   { "name": "Arm L/Heart", "opacity": 255, "blendMode": "normal", "data": "attachment" },
   { "name": "Arm R/", "opacity": 255, "blendMode": "normal", "data": "attachment" },
   { "name": "Arm R/Tattoo", "opacity": 255, "blendMode": "normal", "data": "attachment" },
   { "name": "Head/BASE", "opacity": 255, "blendMode": "normal", "data": "attachment" },
   { "name": "Head/One Eyed", "opacity": 255, "blendMode": "normal", "data": "attachment" },
   { "name": "Hair/BASE", "opacity": 255, "blendMode": "normal", "data": "attachment" },
   { "name": "Hair/Frizzy", "opacity": 255, "blendMode": "normal", "data": "attachment" },
   { "name": "Glove L/A", "opacity": 255, "blendMode": "normal", "data": "attachment" },
   { "name": "Glove R/BASE", "opacity": 255, "blendMode": "normal", "data": "attachment" }
  ],
```
Anyway for the import purposes I think this information is not required.
