### ISSUE TITLE
Crash when undo a new tilemap layer command

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/Attachment-System#64]
`obj == NULL` inside function: 

[`void SetUserDataProperty::onUndo()`](https://github.com/aseprite/aseprite/blob/d590d3f39ad9640aebb876f694420c3f062902d8/src/app/cmd/set_user_data_property.cpp#L48-L54)

It's very possible that this is a Core issue.

**Comment by Gasparoken** [comment]
PR pushed on https://github.com/aseprite/aseprite/pull/3720 to solve this

**Comment by dacap** [comment]
Probably the crash was fixed with https://github.com/aseprite/aseprite/commit/b43f2a34280b64c95a8941bb43ba7b87a77e9c3b, but there are still another problem when we create a new tilemap layer, undo, and then redo:

![Image](https://github.com/aseprite/Attachment-System/assets/39654/b1d6ce78-d227-4cdc-9719-78ee4f6da7f7)

**Comment by Gasparoken** [comment]
I've been looking into this and it seems that the `redo()` command initiates an `App_sitechange` operation after `AddLayer::onRedo()`, the latter function fires the `App_sitechange()` event which is caught by the lua `App_sitechange` defined at `main.lua` (Attachment-System) , and if there is a change defined inside `App_sitechange()` script function, such as an active layer change (for example), then the change is illegal because it is in the middle of the redo operation.
Some possible solutions:
1. Emplace the `App_sitechange()` event at the end of command sequence.
2. Ignoring any change/new commands defined inside `App_sitechange()` script function  in the middle of undo/redo operations.
3. Add `if ev.fromUndo then return end` as first line inside of `App_sitechange()` script function.

What do you think @dacap?

**Comment by dacap** [comment]
Generally we should filter all events that came ev.fromUndo (if a change/sitechange is from an undo/redo, we shouldn’t do anything else), if the 3 option works we should use it.
