### ISSUE TITLE
Navigation through attachments between different folders

### ISSUE THREAD

**Issue by dacap** [aseprite/Attachment-System#91]
We should be able to move through folders (jump folders) using the arrow keys.

Note: don't focus folder buttons (as they will need more key presses to jump to the attachment inside the folder).

**Comment by martincapello** [comment]
If a folder is hidden, should we focus the folder button in this case? Doing so we give the user the chance to open it.

Currently, the left and right arrow keys navigate the tiles of the focused folder. Is the idea to move to the next folder after the user reached the last tile in the current folder? Or is the idea to use up and down keys to navigate between folders?

**Comment by dacap** [comment]
> If a folder is hidden, should we focus the folder button in this case?

No, at least the first approach will be to just navigate tiles (not hidden folders/buttons).

> Is the idea to move to the next folder after the user reached the last tile in the current folder? Or is the idea to use up and down keys to navigate between folders? Or maybe both?

Both. When we reach the end of one folder, we jump to the next one (to any side).
