### ISSUE TITLE
Improve UI to show/edit anchors/reference points on canvas

### ISSUE THREAD

**Issue by dacap** [aseprite/Attachment-System#94]
We can evolve the UI to edit anchors and reference points in the same canvas. Without creating a new dialog and a temporal sprite.

## Goal

The goal of having anchors points between attachments is to be able to switch different instances of each part and locate them in the correct position on the canvas (whatever the other part is).

E.g., A body layer will have anchor points for each arm layer and the head layer and switching different arm/head instances should place them correctly matching the corresponding anchor point <-> reference point.

The reference point is the pivot point of the children part to be matched with the anchor point in the parent.

<img width="421" alt="image" src="https://user-images.githubusercontent.com/39654/232073809-600ff2af-33d3-49ad-babd-f48a01651db7.png">

## Expected UX:

We think that most anchor/reference point relationships (and hierarchy of layers) could be stablished in an on-going process (while we draw the sprite or starting with an already existing sprite) with one command which could be called "Insert Joint," "Set Anchor Points," or "Put a Nail."

This command would do several things at the same time. In few words **Insert Joint should stablish the anchor point <-> reference point relationship** automatically between two layers (asking for a point in the editor only when it's needed).

This is an example of the expected workflow if we start from scratch:

1. We create a new file, a new "Body" layer, and drawing the first body frame of our character
2. Then we create a new "Arm" layer and draw the first frame
3. We put both layer in the correct position and press the "Insert Joint" command:
   1. As both layers don't have any anchor point or reference point stablished, we ask the user for that point
   2. The editor changes to a state (similar to the one in *Edit > New Brush*) to put the joint in the correct position
   3. After that we have the point that will be the anchor point in the body and the reference point in the arm for that specific frame
   4. How do we know that the body is the parent? By default, we can stablish that the layer at the bottom is parent of the layer at the top (but we have to offer a way to change the hierarchy manually if needed)
   5. What happen when there are more layers involved (we'll look that later)
4. Now we create a new frame, duplicate the "Arm" attachment (its reference point will be copied), we insert it on the canvas and modify it, everything goes ok, both points are already defined
   1. In case that we move the arm and use the "Insert Joint" command, the reference point of the arm will be updated to the anchor point position in the body
5. We create another frame, but this time we create a new empty arm attachment, we insert it on the canvas (by default the arm cel could be in the 0,0 position, as the tile uses the whole canvas), we start drawing the new arm from scratch, and move the layer to the correct position
6. Once the new arm is done, we use "Insert Joint", and as the parent already has the anchor position, here we setup the reference point of the arm automatically (exactly where the parent anchor is)
7. We create a new frame, but this time we create a new empty body instance, we draw it and it doesn't have an anchor point for the arm yet, but the arm does have a reference point, if we align the body and the arm correctly in the canvas, "Insert Joint" should set the anchor point automatically for the arm in the body layer where the reference point in the arm already is.

With a two-layers case like this one it looks quite simple, but if we are handling a body, with two arms, a head, and more parts there are other situations (more anchor points at different levels). One possibility would be that this "Insert Joint", when it finds an ambiguous situation, could ask how to resolve it, e.g.:

1. If in the selected point/pixel on the canvas, there are three or more layers, we have to indicate which layers we want to relate.
2. Same if we have one or no layer at all (selecting an empty pixel)
3. If "Insert Joint" is used when both points (anchor <-> reference point) are already in the same position, we can use it just to redefine the point (this will modify the anchor point of the parent something that might not be desirable)

## Future Integration

In the future we have to think if this feature could be a possible initial point for armature/skeleton animations:

* https://community.aseprite.org/t/create-armature-to-easily-animate/7194
* https://community.aseprite.org/t/how-hard-would-it-it-be-make-a-sekeletal-system-for-aseprite/16897

## Required Tasks

- [x] #101
- [x] #102
- [ ] #103
- [x] #104 
- [x] #105 
- [x] #106
- [x] #107

**Comment by Gasparoken** [comment]
> We can evolve the UI to edit anchors and reference points in the same canvas. Without creating a new dialog and a temporal sprite.

A temporal new sprite to edit anchors/ref is still useful when some attachment isn't present on the canvas.

I still think the temporary sprite approach to editing a category's attachment anchors/ref is a good idea and should be kept for quick access to all attachments without having to search them on the canvas (or worst, need  to add them for editing).
I agree that temporary sprite for anchor/ref editing is confusing when:
1. The anchor to add does not have the defined reference point (the position of the child does not make sense)
2. The anchor shows a default attachment (currently index 1) that is not the one desired to correctly position the anchor.

**Comment by Gasparoken** [comment]
I was testing the new UI. IMO the new 'Insert Joint' command is a great addition and simplifies the workflow.
Some issues founded (Aseprite MacOS version):
- The keyboard shortcuts on View > Attachment System > ... doesn't show.
- To draw a new attachment in a new cel, it's needed to add first an empty/duplicate attachment and then positioning that new empty attachment to the cel (via ctrl+Enter), finally we can draw in the cel. Proposal: if we want to draw in an empty tile, it should add a new attachment in the tileset and add that attachment to the active cel.
- 'Insert Joint' command won't show as option the layers which selected pixel coordinate is a transparent color. Proposal: give a 'Manual' alternative as last resort.
- After executing the 'Insert Joint' command and pressing the 'Parent <-> Child' button, the Attachment System Windows do not update the UI correctly. Only if we move the cursor, the user interface is corrected.

**Comment by dacap** [comment]
> To draw a new attachment in a new cel, it's needed to add first an empty/duplicate attachment and then positioning that new empty attachment to the cel (via ctrl+Enter), finally we can draw in the cel. Proposal: to draw on a new empty cel, would be good to automatize the attachment addition to the tileset and the cel.

Yes. There are two steps. The new shortcut to put the attachment in the canvas is Space+C (like "copy attachment to the canvas") but double-clicking the attachment does the job. I've to convert the "Duplicate" to a command yet (so it's accessible through a shortcut) and probably we could offer a "Duplicate and Put Attachment"  (probably without shortcut by default).

> 'Insert Joint' command won't show as option the layers which selected pixel coordinate is a transparent color. Proposal: give a 'Manual' alternative as last resort.

Known issue, actually the command is using the bounds of each attachment (get_shrunken_bounds_of_image) to see if they can be jointed. (Before that I tried with getPixel() to check both solid pixels but it was a worse experience).

> After executing the 'Insert Joint' command and pressing the 'Parent <-> Child' button, the Attachment System Windows do not update the UI correctly. Only if we move the cursor, the user interface is corrected.

All these kind of issues can be annotated/commented in #108 

> The 'Insert Joint' hierarchy logic assumes by default that a layer (A) in front of another layer (B) will be the 'child' layer. This is: 'B' will be the parent of 'A'. Proposal: additional button to reverse the resulting hierarchy?

As we talked, the proposal could be to show a button to reverse the hierarchy or two buttons to choose what hierarchy we prefer. I was thinking about this UI: 1) if there is no hierarchy, we show two buttons (like "Head > Hair" and "Hair > Head"), 2) if the hierarchy is already defined we show "Head > Hair" and other little button "X" to break the hierarchy (just as a tool of last resource to undo a mistake, but it's an option that shouldn't be used in other cases).

> During attachment placement (via ctrl+Enter), the Align Anchors command is activated and all attachments in the frame are modified. Proposal: Do not run Align Anchors during attachment placement.

About this, something planned was to align the hierarchy from the replaced attachment, e.g. if we put a new arm, align the arm to the same pivot (refpoint) and then align the children of the arm, and the hand of the arm (but none of the other elements).

> New feature: the property "being a child of" is shareable with the new 'Insert Joint' command. So the hierarchy can be more flexible than before (old behavior: property "being a child of" were not shareable):

I don't quite understand this one, do you mean that one attachment can have multiple parents?

> This can result in an accidental hierarchy loop, this case will be limited.

:+1: a lot of scenarios can appear because there are no checks yet.

**Comment by Gasparoken** [comment]
>> New feature: the property "being a child of" is shareable with the new 'Insert Joint' command. So the hierarchy can be more flexible than before (old behavior: property "being a child of" were not shareable):

> I don't quite understand this one, do you mean that one attachment can have multiple parents?

- One attachment can have multiple parents, yes.
- But also: a series of attachments (a tileset) can vary its children throughout the series (example: attachment [1] has an anchor to layer A, attachment [2] has an anchor to layer B) . This is new, the old way of defining anchors in an attachment  was to define all attachments with a 'layerId' and a 'position' (center by default), this happened when we added a single anchor to an attachment.
So the same example in the old way would be: the attachment [1] has two anchors corresponding to layer A (position defined) and B (position by default), the attachment [2] has two anchors corresponding to layer A (position by default) and B (position defined).
